# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"

services:
  node:
    container_name: ${CONTAINER_NAME:-resume-service}
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run develop
    user: node
    volumes:
      - .:/srv/app
    environment:
      NODE_ENV: development
      NOT_HOST_MACHINE: 1
      COMMIT_REF: "${COMMIT_REF:-none}"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
